### ISSUE TITLE
Debugger tool for WT Index & data

### ISSUE THREAD

**Issue by czervenka** [windingtree/wiki#102]
We need simple tool to be able to debug hotel data:

- list all hotels from WT Index
- for each entry
    - show links to read-api
    - read and show it's smart contract data,
    - list data files with links (where possible) and
    - warnings about availability or data schema warnings

It would be cool to have this tool as part of Hotel Explorer

**Comment by JirkaChadima** [comment]
I decided to make a standalone app: https://github.com/windingtree/wt-index-debugger/

But it's possible to integrate into the explorer, although it kind of undermines the need for Read API then.

**Comment by JirkaChadima** [comment]
The app is running on https://index-debugger.windingtree.com/, all bugs, requests etc. should go into https://github.com/windingtree/wt-index-debugger/ from now on.

**Comment by kvbik** [comment]
big <3 for the app
