### ISSUE TITLE
Proposal: Basic hotel data format

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wiki#22]
*This is an archived version of https://github.com/windingtree/wt-js-libs/issues/125 for future reference*

The goal of this issue is to reach a consensus on a shape of descriptive hotel data. Inventory (rooms), pricing, availability and booking are *not* part of this issue. After we create a data definition, we will have to formalize it (maybe swagger/openapi descriptor would work) and implement it in this library as additional hotel data and also implement it in the wt-nodejs-api endpoints. It might also make sense to separate the code handling on-chain and off-chain data to multiple methods to make the library more readable and data flow more transparent. The current approach might not be flexible enough when we let our users choose the way of storing their data.

I tried to compare the following standards/specifications and select a minimal necessary and common subset that we could start with. This will also enable us to write adapters for different providers in the future (such as OTA <-> WT) with simple data mapping.

- Our original on-chain data storage [Hotel.sol](https://github.com/windingtree/wt-contracts/blob/v0.1.0/contracts/hotel/Hotel.sol)
- [RoomRanger](https://roomranger.com/) - not public right now
- Expedia's [Property API](https://expediaconnectivity.com/apis/product-management/property-api-contact-expedia-before-adopting-/api-definition.html) and [Product API](https://expediaconnectivity.com/apis/product-management/product-api/quick-start.html)
- [HTNG](http://www.htng.org/?page=technical_specs)
- [SynXis/Sabre](https://developer.sabre.com/sabre_hospitality/apis/soap_apis/hotel/channel_connect/ari)
- [siteminder](https://siteminder.atlassian.net/wiki/spaces/PMSXCHANGEV2/overview)
- [OXI](https://docs.oracle.com/cd/E91116_01/docs/User%20Manual.pdf), https://docs.oracle.com/cd/E91116_01/docs/Communication%20Vendor%20Specification.pdf

The very incomplete comparison and data mapping can be seen on https://docs.google.com/spreadsheets/d/1dqQVvF7IIkurIMSMENbB04Fe2HOxbvI9DgYxnhPoGv8/edit?usp=sharing

# Example data

```
{
  "name": "Example hotel",
  "description": "Luxurious hotel near the city center",
  "contacts": {
    "general": {
      "email": "hotelmanager@example.com",
      "phone": "555-555",
      "url": "https://example.com",
      "ethereum": "0xDAD697274F95F909ad12437C516626d65263Ce47" // or windingtree.eth
    }
  },
  "address": {
    "line1": "Main Street",
    "line2": "",
    "zip": "12345",
    "city": "Capitol city",
    "state": "New York",
    "country": "US"
  },
  "location": {
    "latitude": "52.323475",
    "longitude": "2.665040"
  },
  "timezone": "America/New_York",
  "currency": "USD",
  "images": ["http://example.com/picture-1.png", "http://example.com/picture-2.png"],
  "amenities": ["hot tub", "TV"],
  "createdAt": "ISO8601 timestamp",
  "updatedAt": "ISO8601 timestamp"
}
```

Please, have a look at it @augustol, @czervenka, @kvbik, @MatiasOS

**Comment by carlcook** [comment]
A few minor comments: 

- For amenities, at the hotel level these are things like WIFI, Gym, etc (not TV, spa - they are room type details).
- Having a hotel rating (even if this is self-provided) is probably relevant
- General check-in/check-out policies might be useful at the hotel level as well
- Categories (such as romantic, family, hip, etc) might also be useful
- ZIP code is a US thing (and State isn't a global concept either). Maybe make these more general concepts?

Otherwise, it looks good! If you'd like to discuss what room types often look like, I'm happy to show you our schema for this (by our I mean Traversel's).

**Comment by JirkaChadima** [comment]
Thanks for your input, @carlcook 

- amenities - that's just an example and since it's designed as an array of strings, there's no semantics of the data. But of course, this is meant as hotel-level amenities
- rating - Do you mean something like a star rating? It might actually make sense to have that, it could very quickly narrow down the search results
- check-in/check-out - we will probably add that later, there does not seem to be a concensus on how to represent this type of data.
- categories - sure, why not... It might be helpful in search results - but I think we should then have some sort of enumeration of possible values to keep it reasonable
- zip codes are actually used outside of US as well (https://en.wikipedia.org/wiki/Postal_codes_in_the_Czech_Republic), they're just sometimes called postal codes. I agree that State is not really a transferrable concept, but it won't be a mandatory field, so I think we can keep it
