### ISSUE TITLE
Data signatures

### ISSUE THREAD

**Issue by hynek-urban** [windingtree/wiki#38]
I would like to reopen the discussion about off-chain data signatures.

Data that is being served off-chain (e.g. from https) could (should?) be signed with the hotel's public key. In theory, this would serve two basic purposes:

1. To prove that the data actually comes from the hotel.
2. If the consumer keeps a copy of the data, then in case of disputes this could help him/her prove that the published data at a certain time were in a certain state.

In previous discussions, we have stated that 1. is probably not that valuable because we can utilize existing guarantees at the protocol level (e.g. certificates in case of HTTPS). It occurs to me, though, that number 2. is not covered by protocol properties and could be potentially important.

Thoughts?

**Comment by JirkaChadima** [comment]
Related: https://trello.com/c/wD28KN6p/68-wt-js-libs-off-chain-data-signature-verification

**Comment by kvbik** [comment]
i agree with (2) @hynek-urban - thx for pointing it out!

**Comment by hynek-urban** [comment]
@czervenka I guess you're right. It sounds like for the dispute case, it should be enough to restrict signing to the booking scenario. Singing data at publish time seems unnecessary from this point of view. Let's discard this issue.
