### ISSUE TITLE
RoomType ID oddities

### ISSUE THREAD

**Issue by hynek-urban** [windingtree/wiki#39]
The RoomTypes component in the data format definition is of type "object" where the keys are supposed to be IDs of RoomTypes. These IDs are then again present in the object values (RoomType objects themselves). To me, this seems like unnecessary duplication that has certain drawbacks, such as the need to validate if the IDs are actually equal (as they should be).

Therefore, I suggest to change RoomTypes from an object to an array of RoomType objects (unless there is a reason for it to be an object that I am not aware of).

On a related note, I think the description should be improved somehow. Currently, it reads "Vendor string ID of an object", which sounds a bit strange in the RoomType context. I suggest simply "Vendor string ID" instead.

**Comment by hynek-urban** [comment]
The same goes also for "RatePlans" which have the same structure.

**Comment by JirkaChadima** [comment]
My motivation for this structure had two parts, I think:

1. Automagically deal with duplicate data
2. Make data accessing more efficient

But it might have been a premature optimization because we can modify the looks of the data on the API level for efficiency. The only thing we have to somehow describe or document is handling of dupes.

**Comment by hynek-urban** [comment]
@JirkaChadima I'm not sure if I believe in 2., but 1. is a valid reason to prefer an object over an array (quite obvious, too - don't know why I didn't realize this sooner).

So we could either close this issue and let it be or - as another alternative - simply remove the "id" parameter from RoomType and RatePlan. In this way, we'd retain the implicit handling of duplicities and yet we'd get rid of redundancy and the need to verify data integrity.

**Comment by JirkaChadima** [comment]
My intention with leaving the id in a body of RoomType or RatePlan was to make it easier to read the objects if we decided to serve them as standalone documents.But that does not actually apply (at least not yet), so we can probably get rid of it.

@czervenka Do you have any additional thoughts on this?

**Comment by hynek-urban** [comment]
@JirkaChadima Understood. Btw if by "serve" you mean "serve through an API" then the API can supply the ID without it being in the data model, should the need arise.

**Comment by JirkaChadima** [comment]
I meant `serve` as in having the document lying around in a distributed storage. If you let's say somehow obtain an URI of a particular RoomType, you would have no way of identifying that RoomType only from that one document. But again, that actually does not apply to us, so we can probably omit the id.

I agree that the REST API can (or actually should) modify the shape of data to make them a little nicer for the REST API user and make them compliant with the design of the API.

**Comment by czervenka** [comment]
I like the idea of removing ID from individual roomType / ratePlan structures and inject it in reading API.

Regarding description, I'll fix it, thank you @hynek-urban

**Comment by czervenka** [comment]
Seems that we all aggree. I will fix the data specification and reading API definitions and then create issues in repos of APIs
