### ISSUE TITLE
Describe high-level architecture

### ISSUE THREAD

**Issue by hynek-urban** [windingtree/wiki#66]
Right now, we miss an up-to-date high-level architecture overview. There is https://github.com/windingtree/wiki/blob/master/architecture-hotel.md, but that is no longer accurate given the progress we have made (most notably, there is no mention of the publish / subscribe mechanism and the booking process is described in a misleading way).

The document is written in future tense which makes it hard to bring up-to-date. Therefore, the question arises:

- do we keep this as a historical record of intended functionality and create a new up-to-date high-level architecture overview?
- or do we update the existing document based on the progress in the recent months?

**Comment by hynek-urban** [comment]
@czervenka Any opinions on this?

**Comment by JirkaChadima** [comment]
@czervenka @hynek-urban I think we'll be doing something similar for the Hackathon presentation (thinking of schemas mainly). We should coordinate.

**Comment by JirkaChadima** [comment]
Also, somewhat related: https://blog.windingtree.com/summer-2018-release-the-technical-description-bc4899f0ea0c

**Comment by czervenka** [comment]
We need to rewrite that for sure. Current version will be kept by Git system, so I'd just change the text. I'm going to do that. Thanks for apintment @hynek-urban

**Comment by JirkaChadima** [comment]
Dropped in favour of windingtree/docs#3
