### ISSUE TITLE
Improve uploaders options description

### ISSUE THREAD

**Issue by AugustoL** [windingtree/wiki#68]
I had troubles to understand what the uploaders options can be used, I just registred an account succesfully following the process described here https://github.com/windingtree/wiki/blob/master/developer-guides/registering-hotel.md#creating-an-account but it would be good to have a description about the uploaders options, what can be used for.

**Comment by JirkaChadima** [comment]
The documentation was poor, so I've added the description directly to wt-write-api: https://github.com/windingtree/wt-write-api/commit/46902d95595a356b14bc1582f73e10c75655b4dc

I hope this clears things out. If you had something different in mind, please re-open this issue.
