### ISSUE TITLE
Data versioning

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wiki#73]
Since it is inevitable that we will change the data structure pretty rapidly, we should enforce a declaration of data format version in the data itself.

We should
- declare version of the data somewhere (natural candidate is a document on dataUri, but declaring it on-chain might have some benefits)
- expose the version of data through the read-api
- use semantic versioning
- gracefully work with unsupported data document versions

We can
- reuse the hotel-data-structure version number
- declare minimal support in every release of our tooling (APIs, library)
- figure out how to support more than one version in our tooling (nice to have)
- offer a conversion tool (probably not that important, maybe part of wt-fixtures)
- create a stable link to every data version OAS description (nice to have, it would allow clients to dynamically work with for example data validation)

**Comment by hynek-urban** [comment]
I suggest the following:

- We'll add a field to dataIndex containing the version number of the data structure specification
- Each version of each component of our ecosystem (read api, write api, wt-js-libs, ...) will independently declare which version(s) of the data format they are compatible with (typically not just "minimum requirements" but a range of versions or even just a single version, for ease of validation)
- Within a single data index, hotels of various declared versions can coexist. All the tools must gracefully handle that.

Originally, I was also thinking we'd enhance the notificationUri and bookingUri by version numbers pertaining to their specifications. However, these APIs return their version number on the root ("/") path so I guess that's not necessary at the moment.

**Comment by JirkaChadima** [comment]
I agree with your suggestion, @hynek-urban. I presume we will be using [this version number](https://github.com/windingtree/wiki/blob/master/hotel-data-swagger.yaml#L4)? What will eventually happen when we add airlines (or other type of data)? Will there be two data specs with different version numbers?

Also one question regarding validation comes to mind: If any component supports various versions of a single data spec, it seems actually more flexible to not validata data against the swagger docs (which we wanted), but against a custom hand-crafted schema. Am I right? It sounds kind of scary :-)

And I'm going to end with a thought experiment: Would there be any value in declaring the hotel data version number in a smart contract? It kind of *feels* right to me (because you can cut dead branches early without accessing potentially slow off-chain data), but I'm not really sure if there's a real use case for that in any of our tooling.

**Comment by hynek-urban** [comment]
Yes, that's the version number I had in mind.

As far as non-hotel entries go, that's up for discussion. In my view, it would be easier to keep the things separate (i.e. separate specifications with separate versioning).

As far as your concern wrt. custom hand-crafted schema goes, I guess that's right. However, that's up to whomever develops the component in question :) Also, this is why I presume that in practice, specific versions of our components will be fixed to a single data version number anyway, at least in the foreseeable future. I see this whole thing more as a preparation for the times when backwards compatibility and multiple versions of data will be a real problem than something that needs to be tackled right away in its full breadth.

To reply to your last point, I see the point about having one less "hop" in the chain of queries. On the other hand, the smart contract data would grow a bit, it would make migrations a little more demanding, off-chain storage should typically be faster than on-chain one and to me, intuitively, the data version number belongs right there to the data document itself :) But I admit I'm a bit biased - I mostly do not want to deal with blockchain unless necessary as it's always more complicated than the alternative.

**Comment by JirkaChadima** [comment]
> separate specifications with separate versioning

I agree.

> I see this whole thing more as a preparation for the times when backwards compatibility and multiple versions of data will be a real problem than something that needs to be tackled right away in its full breadth.

Backwards compatibility will of course be a huge task and I have a feeling it will not be solved only with versioning. So yeah, let's keep it simple for the time being.

The last point really was just a though experiment. I agree that it's way easier for all interested parties to deal with it off-chain. My idea behind that is that you would be able to construct a list of hotels with a specific version with a single tool (anything that speaks smart contract) - but I guess there really is no reasonable use case for that, because you need other tools anyway to work with the *actual* (off-chain) hotel data.

**Comment by hynek-urban** [comment]
Ok, it seems we're on the same page. Therefore, I will:

1. Add the field to the data index spec.
2. Update all our components to somehow count with this field.

P.S.: Since writing the last comment, I started to be unsure about the "separate specification" point. Mostly because having a single "Winding Tree Data Specification" document would simplify sharing components between hotels and aerolines. In any way, that doesn't really change anything at the moment.

**Comment by JirkaChadima** [comment]
I agree with what you're going to do.

> P.S.: Since writing the last comment, I started to be unsure about the "separate specification" point. Mostly because having a single "Winding Tree Data Specification" document would simplify sharing components between hotels and aerolines. In any way, that doesn't really change anything at the moment.

Let's do hierarchical versioning and delibarately put ourselves into dependency hell :-) To be serious though: There are serious pros and cons for both approaches (typically ability to iterate vs. user-friendliness) and it really depends on how it's going to be used. If we are able to achieve sort of sem-ver of particular specs, I can easily imagine a "meta" spec with a single version. The question as always is, if it's not an overkill.

**Comment by hynek-urban** [comment]
The suggested steps have been implemented. Deployment to the "demo" and "playground" environment waits for the post-hackathon data reset. Therefore, I'm closing this issue.
