### ISSUE TITLE
Hotel category (0.5sp)

### ISSUE THREAD

**Issue by mikozza** [windingtree/wiki#85]
I propose to add hotel category field to hotel data and define enum list of hotel categories like: hotel, hostel, resort..which would be used in the data and ake this list available on hosted URL as part of the documentation,

https://github.com/windingtree/wiki/blob/ebf034be7464ebb1244ed77e97b08996d986da40/hotel-data-swagger.yaml#L81

**Comment by JirkaChadima** [comment]
This has been on our [todo](#28) list for a long time, but we didn't have a reasonable enum at hand. I'm not sure how flexible we might be with enums in [OAS](https://swagger.io/docs/specification/about/) in regards of hosting only an enum but we'll sure take a look.

Do you have any tips on the possible sources of such enumeration? We can probably scavenge [loads of APIs](https://github.com/windingtree/wiki/blob/master/hotel-data-resources.md) for that but it would be nice to have a starting point. Thank you!

**Comment by mikozza** [comment]
We will prepare something and post it here.

**Comment by Honza65** [comment]
Here are the hotel categories.

Hostel
Hotel
Camp
Academy
Ashram
Barn
Bed and Breakfast
Boat
Bungalow
Cabin
Campsite
Campus
Castle
Chalet
Cottage
Farm
Hostel
Hotel
House
Inn
Lodge
Monastery
Motel
Ranch
Resort
Retreat center
School
Temple
Villa
Haunted House
Dependence
Botel
Holiday Homes
Guest House
Private Home

**Comment by czervenka** [comment]
I think that the set of possible values needs to be discussed more widely and compared to current standartds.

Let's add few the most common values and add an option of "other" for the rest.

**Comment by JirkaChadima** [comment]
So I came through the excellent list provided by @Honza65 and all of the following:

- OTA PCT enum
- expedia typeOfRoom enum
- expedia partner category enum

and settled on this:

```
apartment
bed and breakfast
boat
cabin
camp
holiday home
hostel
hotel
house
inn
mobile home
motel
other
spa
```

This will be an enum which is coincidentally in english. It won't be provided with translations in the data itself.

**Comment by mikozza** [comment]
I think thats fine, the question is now if we should reffer to this enums by string or int in the data?

**Comment by JirkaChadima** [comment]
I would go with strings as it's usually easier to debug

**Comment by JirkaChadima** [comment]
I will use this as a tracking issue.

In order to add support for this throughout the platform, we further need to:

* [ ]   show support for this in wt-fixtures
* [ ]   bump swagger docs in wt-read-api + test support for this
* [ ]   bump swagger docs in wt-write-api + test support for this
* [ ]   show the field in the hotel explorer

Non critical

* [ ]   bump swagger docs in wt-search-api + test support for this
* [ ]   add support for search by category in wt-search-api

**Comment by JirkaChadima** [comment]
Support for this should work everywhere, closing for now. It will land in the next release.
