### ISSUE TITLE
Room and hotel amenity definitions (1.5sp)

### ISSUE THREAD

**Issue by mikozza** [windingtree/wiki#88]
I propose to define short lists of required amenities/attributes which should be required for each room type or hotel.

For example room size, room floor level, internet, barrier-free etc. To enable fast filtering in future and data consistency. The custom attributes however shell be still possible as well.

https://github.com/windingtree/wiki/blob/ebf034be7464ebb1244ed77e97b08996d986da40/hotel-data-swagger.yaml#L432

**Comment by JirkaChadima** [comment]
This might get easily out of hand. I can think of at least these things that might come into play:

- amenities such as TV, internet - yes/no stuff
- room floor level etc. - some non-binary value
- paid amenities - how much do I have to pay for TV? Or is it free?
- mandatory/non-mandatory fields - we have to be very careful with this to not put up a barrier for adoption
- custom attributes - that's always hard to do and unify across the platform - it might undermine the whole idea of easy searchability

**Comment by mikozza** [comment]
I agree that there's not an obvious exact path to stick to. But it thinks that it's important to open discussion about it and propose the genesis structures, which could be improved over time.

The current structure with strings without any definitions is a way to chaos, I would preserve them but renamed them to "tags" and let anyone assign custom tags.

We are preparing some definition as suggestions. We will post it here soon.

**Comment by mikozza** [comment]
For start maybe something like this. All booleans except of room size which is int.

Hotel
  | Free Wi-Fi
  | Bar
  | Restaurant
  | Free parking
  | 24-hour front desk
  | Aiport shuttle
  | Swimming pool
  | Air conditioning
  | Room service
  | Terrace
  | Kid´s day care
  | Spa services
Room
  | Air conditioning
  | Balcony
  | TV
  | Private bathroom
  | Terrace
  | Room size (int)
  | Wheelchair accessible
  | Crib
  | Kitchen
  | Pets
  | Free Wi-Fi

**Comment by czervenka** [comment]
Cool, thanks @mikozza.

To the obligatory properties in hotel/room data, I agree with @JirkaChadima that we need to be really careful.

Let's start with three lists with fixed set of possible values (enum):
- free amenities
- paid amenities
- additional properties (room size, room floor level)
... and a "custom tags" list (I love the idea)

For reference here are enums defined in OTA standard (filtered carefully by my memory):
- Hotel
    - Recreational activities - [RecreationService_Enum](http://opentravelmodel.net/pubs/content/specifications/downloads/noregister/2018A/2_0/RecreationService_Enum.html)
    - Business services
    - Amenities
    - Security features (e.g. alarm smoke detector, 2nd lock on guest doors, ..) - [SecurityFeature_Enum](http://opentravelmodel.net/pubs/content/specifications/downloads/noregister/2018A/2_0/SecurityFeature_Enum.html)
    - Disability features (e.g. Elevators have Braille Instructions, ...) - [DisabilityFeature_Enum](http://opentravelmodel.net/pubs/content/specifications/downloads/noregister/2018A/2_0/DisabilityFeature_Enum.html)

- Room
    - Disability features (e.g. Elevators have Braille Instructions, ...) - [DisabilityFeature_Enum](http://opentravelmodel.net/pubs/content/specifications/downloads/noregister/2018A/2_0/DisabilityFeature_Enum.html)
    - Recreational service (e.g. bike rental) - [RecreationService_Enum](http://opentravelmodel.net/pubs/content/specifications/downloads/noregister/2018A/2_0/RecreationService_Enum.html)
    - Security features (e.g. alarm smoke detector, 2nd lock on guest doors, ..) - [SecurityFeature_Enum](http://opentravelmodel.net/pubs/content/specifications/downloads/noregister/2018A/2_0/SecurityFeature_Enum.html)

**Comment by czervenka** [comment]
There was a short internal discussion in the core team, here are the outcomes: Let's implement the most basic and standard solution and leave opened pull request for discussion for - let's say - two weeks.

**Comment by JirkaChadima** [comment]
I totally agree with @czervenka 's proposal with multiple sets. I don't think I'm quite ready to put this into a spec, but the actual data I think might look like below. My thinking is that it might be the same structure for both hotel and room type.

```js
{
    "properties": [ // objective statements about the property, only from a prepared enumeration
       {"name": "pool-size", "value": 123},
       {"name": "room-size", "value": 123},
       {"name": "view", "value": "southeast"},
       {"name": "ocean-distance", "value": 200},
    ],
    "amenities": [ // free yes-no services, only from a prepared enumeration
       "wi-fi", "pool", "terrace", "tv"
    ],
    "ancilliaries": [ // extra paid services
       {"name": "extra-pillow", 'price": 10, "priceType": "perStay"},
       {"name": "beercase", 'price": 20, "priceType": "perPiece"},
    ],
    "tags": [ // free form text
      "first-tag", "second-tag"
    ],
}
```

My questions are:
1. Does it make sense to make a difference between properties and amenities? If not, let's go with the properties richer structure and accept true/false as the value.
1. Anciliaries are undefined wrt enumerations for now. I think they are business-related and will eventually need to contain description, images and some more polish. But that hits the note of proper localization which I'd rather not go into at the moment.

If I'd had to make a decision right now, I'd drop amenities in favour of proposed properties and not implement anciliaries and tags now. What do you guys think?

**Comment by czervenka** [comment]
I like the division to the four categories as well as the format.

Given the sample values sent by @mikozza, the most important lists are "properties" and "amenities". Am I right @mikozza ?

**Comment by JirkaChadima** [comment]
@mikozza We decided to move anciliaries to a separate issue with which we will deal later, is that OK? In this batch of platform updates, we will only add `properties`, `amenities` and `tags`. I will inspect the enumerations in the coming days and hopefully come up with something sensible.

**Comment by mikozza** [comment]
np for me, upgrade to any standard is big step forward for now !

**Comment by JirkaChadima** [comment]
For tracking of future progress:

- [ ] Merge https://github.com/windingtree/wiki/pull/97
- [ ] Bump the data spec version
- [ ] Add/verify support in wt-read-api
- [ ] Add sample data in wt-fixtures
- [ ] Add/verify support in wt-write-api
- [ ] Add/verify support in wt-search-api
- [ ] Add/verify support in wt-hotel-explorer

**Comment by JirkaChadima** [comment]
Follow ups (separated for unforeseen complexities):

- #99 
- #98 
- #96

**Comment by JirkaChadima** [comment]
I'm closing this for now and all other debate should happen in the follow up issues.
